title: Minipart
email: your-email@example.com
description: >-
  A multilingual website dedicated to mining-related projects and open science.

baseurl: "" # no subfolder
url: "" # set your production URL here if deploying

theme: minima

plugins:
  - jekyll-feed
  - jekyll-polyglot

# Polyglot multilingual config
languages: ["sr", "en"]
default_lang: "sr"

# Important! This keeps Serbian at `/` instead of `/sr/`
parallel_localization: true

# Skip localizing these folders
exclude_from_localization:
  - assets
  - images
  - css
  - js

# Include all pages from this folder
include:
  - _pages

# Optional but helpful: set default layout for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
